# Generated by Django 5.2.1 on 2025-06-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotParkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_slot', models.CharField(max_length=10)),
                ('jenis_kendaraan', models.CharField(choices=[('mobil', 'Mobil'), ('motor', 'Motor')], max_length=10)),
                ('tersedia', models.BooleanField(default=True)),
                ('kode_unik', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiketParkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_masuk', models.DateTimeField(auto_now_add=True)),
                ('kode_unik', models.CharField(blank=True, max_length=8, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkir.slotparkir')),
            ],
        ),
        migrations.CreateModel(
            name='LogTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_log', models.DateTimeField(auto_now_add=True)),
                ('aksi', models.CharField(max_length=100)),
                ('tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkir.tiketparkir')),
            ],
        ),
    ]
