# Generated by Django 5.2.1 on 2025-05-31 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotParkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_slot', models.CharField(max_length=10)),
                ('jenis_kendaraan', models.CharField(choices=[('mobil', 'Mobil'), ('motor', 'Motor')], max_length=10)),
                ('tersedia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiketParkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_unik', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('waktu_masuk', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkir.slotparkir')),
            ],
        ),
    ]
