# Generated by Django 5.2.1 on 2025-06-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotparkir',
            old_name='nomor_slot',
            new_name='kode_slot',
        ),
        migrations.AlterField(
            model_name='slotparkir',
            name='jenis_kendaraan',
            field=models.CharField(choices=[('motor', 'Motor'), ('mobil', 'Mobil')], max_length=10),
        ),
    ]
