# Generated by Django 5.2.1 on 2025-06-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotparkir',
            name='kode_unik',
        ),
    ]
