# Generated by Django 5.2.1 on 2025-06-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0002_rename_nomor_slot_slotparkir_kode_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotparkir',
            old_name='kode_slot',
            new_name='nomor_slot',
        ),
        migrations.AlterField(
            model_name='slotparkir',
            name='jenis_kendaraan',
            field=models.CharField(choices=[('mobil', 'Mobil'), ('motor', 'Motor')], max_length=10),
        ),
    ]
