# Generated by Django 5.2.1 on 2025-06-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0002_remove_slotparkir_kode_unik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiketparkir',
            name='kode_unik',
        ),
        migrations.AddField(
            model_name='slotparkir',
            name='kode_unik',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
