# Generated by Django 5.2.1 on 2025-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotParkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_slot', models.CharField(max_length=10)),
                ('jenis_kendaraan', models.CharField(max_length=20)),
                ('tersedia', models.BooleanField(default=True)),
                ('kode_unik', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
